version: 2
jobs:
  deploy_production:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install node deps
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Install awscli
          command: sudo apt-get -y -qq install awscli
      - run:
          name: BUIDL AND DEPLOY ALL, ALL YOUR BASE R BELONG TO US
          command: yarn run deploy-all
  deploy:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install node deps
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Install awscli
          command: sudo apt-get -y -qq install awscli
      - run:
          name: BUIDL AND DEPLOY STAGING
          command: yarn run deploy-staging

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
      - deploy_production:
          filters:
            tags:
              only: /^v.*$/
            branches:
              ignore: /.*/
